# Generated by Django 5.2.12 on 2026-03-08 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdb_id', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('original_title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('tagline', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('Released', 'Released'), ('Post Production', 'Post Production'), ('In Production', 'In Production'), ('Planned', 'Planned'), ('Canceled', 'Canceled')], default='Released', max_length=50)),
                ('release_date', models.CharField(blank=True, max_length=20, null=True)),
                ('runtime', models.IntegerField(blank=True, null=True)),
                ('original_language', models.CharField(blank=True, db_index=True, max_length=10, null=True)),
                ('spoken_languages', models.JSONField(blank=True, default=list)),
                ('budget', models.BigIntegerField(blank=True, null=True)),
                ('revenue', models.BigIntegerField(blank=True, null=True)),
                ('vote_average', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('vote_count', models.IntegerField(blank=True, null=True)),
                ('imdb_rating', models.DecimalField(blank=True, db_index=True, decimal_places=1, max_digits=4, null=True)),
                ('imdb_votes', models.IntegerField(blank=True, null=True)),
                ('popularity', models.DecimalField(blank=True, db_index=True, decimal_places=4, max_digits=10, null=True)),
                ('poster_path', models.CharField(blank=True, max_length=255, null=True)),
                ('trailer_url', models.URLField(blank=True, null=True)),
                ('genres', models.JSONField(blank=True, default=list)),
                ('cast', models.JSONField(blank=True, default=list)),
                ('producers', models.JSONField(blank=True, default=list)),
                ('writers', models.JSONField(blank=True, default=list)),
                ('production_companies', models.JSONField(blank=True, default=list)),
                ('production_countries', models.JSONField(blank=True, default=list)),
                ('director', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('director_of_photography', models.CharField(blank=True, max_length=255, null=True)),
                ('music_composer', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-imdb_rating'],
                'indexes': [models.Index(fields=['imdb_rating', 'popularity'], name='cinex360_mo_imdb_ra_41ca49_idx'), models.Index(fields=['status', 'original_language'], name='cinex360_mo_status_32870a_idx')],
            },
        ),
    ]
